//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RsImgSeg.rc
//
#define IDS_PRJVIEWH_PRJ                1
#define IDS_PRJVIEWH_PRJ2               2
#define IDS_PRJVIEWH_Content            3
#define IDS_PRJVIEWH_Content2           4
#define IDS_IMGVIEWH_Name               5
#define IDS_IMGVIEWH_Band               6
#define IDS_IMGVIEWH_Resolution         7
#define IDS_IMGVIEWH_Name2              8
#define IDS_IMGVIEWH_Band2              9
#define IDS_IMGVIEWH_Unit               10
#define IDS_IMGVIEWH_Resolution2        11
#define IDS_IMGVIEWH_CellType           12
#define IDS_IMGVIEWH_Unit2              13
#define IDS_IMGVIEWH_CellType2          14
#define IDS_IMGVIEWH_Line               16
#define IDS_IMGVIEWH_Line2              17
#define IDS_IMGVIEWH_Column             18
#define IDS_IMGVIEWH_Column2            19
#define IDS_THEMVIEWH_Name              21
#define IDS_THEMVIEWH_Content           22
#define IDS_THEMVIEWH_Name2             23
#define IDS_ProjType_LonLat             24
#define IDS_ProjType_UTM                25
#define IDS_ProjType_Albers_Conical_EQ_Area 26
#define IDS_ProjType_Lambert_Conformal_Conic 27
#define IDS_ProjType_Equirectangular    28
#define IDS_ProjType_Miller_Cylindrical 29
#define IDS_ProjType_V_D_Grinten_I      30
#define IDS_ProjType_Oblique_Mercator   31
#define IDS_ProjType_Polar_Srereographic 32
#define IDS_UNIT_MM                     33
#define IDS_UNIT_MilliMeter             34
#define IDS_UNIT_Meter                  35
#define IDS_UNIT_Second                 36
#define IDS_UNIT_Degree                 37
#define IDS_UNIT_DMS                    38
#define IDS_UNIT_Foot                   39
#define IDS_UNIT_Minute                 40
#define IDS_UNIT_Radian                 41
#define IDS_UNIT_GRAD                   42
#define IDS_UNIT_KM                     43
#define IDS_UNIT_KiloMeter              44
#define IDS_UNIT_DM                     45
#define IDS_UNIT_DeciMeter              46
#define IDS_UNIT_CM                     47
#define IDS_UNIT_CentiMeter             48
#define IDS_UNIT_Inch                   49
#define IDS_UNIT_Yard                   50
#define IDS_UNIT_SeaMile                51
#define IDS_UNIT_Mile                   52
#define IDS_PrjInfo_ItemHeader          53
#define IDS_PrjInfo_ProjType            54
#define IDS_PrjInfo_Resolution          55
#define IDS_PrjInfo_LowLeft             56
#define IDS_PrjInfo_UpperRight          57
#define IDS_PrjInfo_Size                58
#define IDS_CellType_UINT8              59
#define IDS_CellType_UINT16             60
#define IDS_CellType_UINT32             61
#define IDS_CellType_INT8               62
#define IDS_CellType_INT16              63
#define IDS_CellType_INT32              64
#define IDS_CellType_IEEE4              65
#define IDS_CellType_IEEE8              66
#define IDS_CellType_1BIT               67
#define IDS_Level_Pixel                 68
#define IDS_Level_Scene                 69
#define IDS_Level_New                   70
#define IDS_ImgBand_Weight              71
#define IDS_UNCLASSIFIED                72
#define IDS_PrjDlgFilterName            73
#define IDS_OpenPrjDlgName              74
#define IDS_SavePrjDlgName              75
#define IDS_ProjType_Mercator           76
#define IDS_THEMVIEWH_Content2          77
#define IDS_ProjType_Gauss_Kruger       78
#define IDS_ProjType_Polyconic          79
#define IDS_ProjType_EQ_Dist_Conic      80
#define IDS_ProjType_Transverse_Mecator 81
#define IDS_ProjType_StereoGraphic      82
#define IDS_ProjType_Lambert_Azimuthal_EQ_Area 83
#define IDS_ProjType_Azimuthal_EQ_Dist  84
#define IDS_ProjType_Gnomonic           85
#define IDS_ProjType_Orthographic       86
#define IDS_ProjType_General_VER_NS_Perspective 87
#define IDS_ProjType_Sinusoidal         88
#define IDS_TEX_MATRIX                  89
#define IDS_TEX_CALMAT                  90
#define IDS_TEX_NOEIGEN                 91
#define IDS_ExpSegMainPgsName           94
#define IDS_ExpClsMainPgsName           95
#define IDS_OpenOrgMsi                  96
#define IDS_OpenMsiFilter               97
#define IDS_PRJFILENAME_FAIL            98
#define IDS_PrjModifyPrompt             99
#define IDS_ObjID                       100
#define IDS_BestClass                   101
#define IDS_SecondClass                 102
#define IDS_ThirdClass                  103
#define IDS_ClassID                     104
#define IDS_Membership                  105
#define IDS_StatFeature                 106
#define IDS_ExpFeature                  107
#define IDS_ClsName                     108
#define IDS_CalObjFtr                   109
#define IDS_SETLEVEL_FAIL               110
#define IDS_LineErr                     111
#define IDS_LineCellErr                 112
#define IDS_BandErr                     113
#define IDS_ProjType_LonLat2            115
#define IDS_ProjType_UTM2               116
#define IDS_ProjType_Albers_Conical_EQ_Area2 117
#define IDS_ProjType_Lambert_Conformal_Conic2 118
#define IDS_ProjType_Equirectangular2   119
#define IDS_ProjType_Miller_Cylindrical2 120
#define IDS_ProjType_V_D_Grinten_I2     121
#define IDS_ProjType_Oblique_Mercator2  122
#define IDS_CellType_INT33              123
#define IDS_CellType_IEEE5              124
#define IDS_CellType_IEEE9              125
#define IDS_CellType_1BIT2              126
#define IDS_Level_Pixel2                127
#define IDS_Level_Scene2                128
#define IDS_Level_New2                  129
#define IDS_ImgBand_Weight2             130
#define IDS_UNCLASSIFIED2               131
#define IDS_PrjDlgFilterName2           132
#define IDS_OpenPrjDlgName2             133
#define IDS_SavePrjDlgName2             134
#define IDS_ProjType_Mercator2          135
#define IDS_ProjType_Gauss_Kruger2      136
#define IDS_ProjType_Polyconic2         137
#define IDS_ProjType_EQ_Dist_Conic2     138
#define IDS_ProjType_Transverse_Mecator2 139
#define IDS_ProjType_StereoGraphic2     140
#define IDS_ProjType_Lambert_Azimuthal_EQ_Area2 141
#define IDS_ProjType_Azimuthal_EQ_Dist2 142
#define IDS_ProjType_Gnomonic2          143
#define IDS_ProjType_Orthographic2      144
#define IDS_ProjType_General_VER_NS_Perspective2 145
#define IDS_ProjType_Sinusoidal2        146
#define IDS_TEX_MATRIX2                 147
#define IDS_TEX_CALMAT2                 148
#define IDS_TEX_NOEIGEN2                149
#define IDS_ExpSegMainPgsName2          150
#define IDS_ExpClsMainPgsName2          151
#define IDS_ProjType_Polar_Srereographic2 152
#define IDS_UNIT_MM2                    153
#define IDS_UNIT_MilliMeter2            154
#define IDS_UNIT_Meter2                 155
#define IDD_SELLEVEL                    155
#define IDS_UNIT_Second2                156
#define IDS_UNIT_Degree2                157
#define IDS_UNIT_DMS2                   158
#define IDS_UNIT_Foot2                  159
#define IDS_UNIT_Minute2                160
#define IDS_UNIT_GRAD2                  162
#define IDS_UNIT_KM2                    163
#define IDS_UNIT_KiloMeter2             164
#define IDS_UNIT_DM2                    165
#define IDS_UNIT_DeciMeter2             166
#define IDS_UNIT_CM2                    167
#define IDS_UNIT_CentiMeter2            168
#define IDS_UNIT_Inch2                  169
#define IDS_UNIT_Yard2                  170
#define IDS_UNIT_SeaMile2               171
#define IDS_UNIT_Mile2                  172
#define IDS_PrjInfo_ItemHeader2         173
#define IDS_PrjInfo_ProjType2           174
#define IDS_PrjInfo_Resolution2         175
#define IDS_PrjInfo_LowLeft2            176
#define IDS_PrjInfo_UpperRight2         177
#define IDS_PrjInfo_Size2               178
#define IDS_CellType_UINT9              179
#define IDC_CurManualClassify           193
#define IDC_SliderCompact               1010
#define IDC_SegMode                     1025
#define IDC_Scale                       1035
#define IDC_ShapeWeight                 1036
#define IDC_LayerListBox                1037
#define IDC_BandWeight                  1039
#define IDC_COMBO_LEVEL                 1042
#define IDC_Tab                         1111
#define IDC_ImgListCtrl                 1370
#define IDC_StaticSetW                  1371
#define IDC_ClassBaseSeg                1409
#define IDC_LevelAbove                  1424
#define IDC_LevelBelow                  1425
#define IDC_ReferToGB                   1426
#define IDC_FilePath                    1465
#define IDC_Alias                       1740
#define IDC_CBaseSegGB                  1772
#define IDC_SliderShape                 1841
#define IDC_CompactWeight               1842
#define IDC_SmoothWeight                1843
#define IDI_ICON2                       2007
#define IDC_COMBO1                      2008
#define IDR_XMLSET_MENU                 2011
#define IDC_CMB                         2023
#define IDS_PixelMerge                  2026
#define IDD_DIALOG1                     2027
#define IDI_ICON3                       2031
#define IDI_SELITEM                     2032
#define IDS_MainProgressName            2033
#define IDC_FlipClass                   2035
#define IDC_EDIT6                       2039
#define IDC_COMBO2                      2041
#define IDC_CHECK2                      2047
#define IDC_FtrVarTree                  4001
#define IDD_IMGSEGDLG                   13008
#define IDD_LEVELDELDlg                 13009
#define IDC_SPIN4                       13015
#define IDS_TYPE_LOC                    24464
#define IDS_UNIT_Radian2                24467
#define IDD_SELCLASS                    24469
#define IDC_LEVERLIST                   24474
#define IDI_ICON1                       24476
#define IDS_SubProgressName             24479
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_Creat_MaskImg                32776
#define ID_Create_MaskImg               32777
#define IDC_BTNCLEAR                    32849
#define IDC_COORDINATES                 34466
#define IDC_BUTTON1                     34468
#define IDC_BUTTON2                     34469
#define IDS_NEWPROJECT                  61218
#define IDS_INITPRJINF_FAIL             61220
#define IDS_SAVEPRJINF_FAIL             61221
#define IDS_NEWPRJ_FAIL                 61222
#define IDS_OPENPRJ_FAIL                61223
#define IDS_LEVEL_NO                    61224
#define IDS_EDITMINMEMB                 61226
#define IDS_SETNNSLOPE                  61227
#define IDS_EDITFTRPARA                 61228
#define IDS_MINMEMBSHIP                 61229
#define IDS_NNSLOPE                     61230
#define IDS_FTRDIST                     61231
#define IDS_MEMBRANGE                   61232
#define IDS_SLOPERANGE                  61233
#define IDS_EDITMEMB_FAIL               61234
#define IDS_SETSLOPE_FAIL               61235
#define IDS_SETBRTCHNL_FAIL             61236
#define IDS_CLSCURLAY_FAIL              61237
#define IDS_MSI_FILE                    61238
#define IDS_FILEISNULL                  61239
#define IDS_EXPORTCLS_FAIL              61240
#define IDS_PRESS_TO8                   61242
#define IDS_PRESS_TO16                  61243
#define IDS_PRESS_TO32                  61244
#define IDS_PRESS_TO64                  61245
#define IDS_PRESS_TO128                 61246
#define IDS_PRESS_NO                    61247
#define IDS_PRESS_TO256                 61248
#define IDS_EDITTEXPARA_FAIL            61249
#define IDS_EDITNNFTR_FAIL              61250
#define IDS_LOADCLSXML_FAIL             61254
#define IDS_ISDEL_ALLSMPL               61255
#define IDS_DELALLSMPL_FAIL             61256
#define IDS_DELCLSSMPL_FAIL             61257
#define IDS_APPSNN_FAIL                 61258
#define IDS_EXPTSMPL_FAIL               61259
#define IDS_EXPTSMPL_SUCES              61260
#define IDS_SMPL_FILE                   61261
#define IDS_IMPTSMPL_FAIL               61262
#define IDS_GenPrjInfo                  61263
#define IDS_GeocodeInfo                 61264
#define IDS_ImgLayer                    61265
#define IDS_ThematicLayer               61266
#define IDS_TYPE_NOPAR                  61267
#define IDS_TYPE_JWD                    61268
#define IDS_TYPE_DD                     61269
#define IDS_TYPE_PRJ                    61270
#define IDS_TYPE_XYZ                    61271
#define IDS_pixel                       61272
#define IDS_kilometer                   61273
#define IDS_meter                       61274
#define IDS_centimeter                  61275
#define IDS_LEGSIZE_ISPOS               61276
#define IDS_Sample                      61277
#define IDS_UnClassify                  61278
#define IDS_NoSample                    61279
#define IDS_Undefined                   61280
#define IDS_Pixel_Level                 61282
#define IDS_Scene_Level                 61292
#define IDS_VALIDCLS_NULL               61293
#define IDS_EXPTLEG_FAIL                61300
#define IDS_SELCLS_FAIL                 61301
#define IDS_SELFTR_FAIL                 61302
#define IDS_SMPL_ISREPLC                61305

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2015
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2056
#define _APS_NEXT_SYMED_VALUE           2012
#endif
#endif
